### PR TITLE
Added organizer info (Lucy)

### PR DESCRIPTION
**Pull request by e9t**
Adding myself for #9!

### CODE REVIEW

**Comment by mhagiwara** [comment]
looks good to me. We may want to put a link to KoNLPy.

**Comment by alvations** [comment]
LGTM.

**Comment by e9t** [comment]
Just add the link to KoNLPy - thanks @mhagiwara!

**Comment by alvations** [comment]
Merged @e9t 's profile.

Let's cross-check each others profile and then merge them =)

**Pull request merged**
